GENRE_RENAME_GROUPS = {
    "Acoustic": [
        "acoustic", 
        "guitar",
        "electroacoustic",
    ],
    "Alternative & Indie Rock": [
        "alternative",
        "alternative rock",
        "alternative/indie",
    ],
    "Ambient": [
        'ambiente',
        'nature',
        "ambiance",
        "ambient",
        "ambient / new age - meditation",
        "background music",
        "chill",
        "chill out",
        "chillhop",
        "chillout",
        "cosmic",
        "dark ambient",
        "easy listening",
        "electronic: ambient",
        "lullaby",
        "nature sounds",
        "soundscape",
        "wave",
        "relaxation",        
    ],
    "Audiobooks": [
        "audiobook", 
        "audiobooks",
        'fiction',
        'drama'        
        ],
    "Brazilian": ["brazilian", "pagode"],
    "Christian/Gospel": [
        "christian/gospel",
        'christian'

    ],
    "Christmas/holiday": [
        "christmas",
        'holiday',
    ],
    "Cello": ["cello"],
    "Classical": [
        "bach",
        "baroque",
        "classic",
        "classica",
        "classical",
        "classical music",
        "classique",
        "clásica",
        "flute choir",
        "klassik",
        "modern classical",
        "orchestra",
        "orchestral",
        "orchestredeparis",
        "romantic",
        "symphony",
    ],
    "Comedy": ["comedy"],
    "Contemporary classical": [
        "classical crossover",
        "contemporary",
        "contemporary classical",
        "modern classical",
    ],
    "Country": ["country", "bluegrass", "country rock"],
    "Disco": ["disco"],
    "Educational & Informative": ["business", "news", "science", "technology"],
    "Electronic": [
        "8bit",
        "deep tech house",
        "idm",
        "acid house",
        "nightbass",
        "ebm",        
        "electronic rock",
        'chillstep',
        'electronic: electro house',
        'synth',
        'electro swing',    
        "electronique : electro",
        "3000 bass",
        "beat",
        "beats",
        "chill",
        "chill house",
        "electronic groove",
        "electronic pop",
        "electronica",
        "electrónica",
        "elektro",
        "eletrônica",
        "elettronica",
        "field recording",
        "fusion",
        "future",
        "lo-fi",
        "lofi",
        "mixtape",
        "synthwave",
        "the broadest beats",
    ],
    "Electronic Dance Music (EDM)": [
        "futurebass",
        "dance - house - tech / minimal",
        "dance : hardstyle",
        'melodic deep',
        'future bounce',
        'dance | house | tech house',    
        '"dance & electronic" (dance/techno/disco)',
        "afro house",
        "base",
        "bass",
        "bass music",
        "dance",
        "dance %7c techno",
        "dance & edm",
        "dance & electronic",
        "dance & electronic (dance/techno/disco)",
        "dance - electro",
        "dance - techno",
        "dance e edm",
        "dance en edm",
        "dance y edm",
        "dance | techno",
        "dance/electronic",
        "dance/house",
        "dance/house/techno",
        "deep tech",
        "downtempo",
        "dubstep",
        "edm",
        "electro",
        "electronic",
        "electronic groove",
        "electronic music",
        "electronica",
        "electronica/dance",
        "electrónica",
        "eletrônica",
        "ethereal techno",
        "future garage",
        "glitch hop",
        "hard dance",
        "hardcore",
        "hardstyle",
        "indie dance",
        "minimal",
        "nu disco",
        "organic house",
        "tropical house",
        "twerk",
        'big room',
        'moombahton',
        'hybrid trap',
        'bounce',
        'melbourne bounce',
        'jersey club',
        'midtempo',
        'chill trap',
        'slap house',
        'house - electro',
        'nu-disco',
        'happy hardcore',        
    ],
    "Flute": ["flute"],
    "Folk": ["folk"],
    "Folk/Singer-Songwriter": [
        "folk",
        "folk & singer-songwriter",
        "pop (singer/songwriter)",
        "singer songwriter",
        "singer-songwriter",
        "singer/songwriter",
    ],
    "Hip-hop": [
        "grime",
        "hip hop",
        "hip hop/rap",
        "hip-hop",
        "hip-hop & rap",
        "hip-hop/rap",
        "hiphop",
        "jazz hop",        
        "lofi hip hop",
        "hiphop/rap",
        "rap",
        "rap/hip hop",
        "rap/hip-hop",
        "trap",
        "trap brasileiro ®",
        "triphop",
        'rap & hip-hop',
        "hip hop y rap",

    ],
    "House": [
        'babylon house',
        'tech house - deep tech',
        'nudisco',
        'disco house',
        'indie dance / nu disco',    
        "house",
        "bass house",
        "club",
        "dance - house",
        "dance/house",
        "deep",
        "deep house",
        "deephouse",
        "disco housetechhouse",
        "electro house",
        "electronic house",
        "future",
        "future bass",
        "future house",
        "g-house",
        "house ",
        "house music",
        "jackin house",
        "melodic house",
        "organic house",
        "progressive house",
        "tech house",
        "tech-house",
        "techhouse",
        'garage',
        'uk garage',
        'ukg',        
        "tribal house",
        "soulful house",
        "house - deep",        
    ],
    "Indie": ["indie", "indie pop", "indie rock"],
    "Instrumental": [
        "instrumental",
        "beat & instrumental", 
        "beats"
    ],
    "Jazz/Blues": [
        "bebop",
        "blues",
        "jazz",
        "jazz & blues",
        "jazz education",
        "smooth jazz",
    ],
    "Latin": [
        "latin", 
        "latin / urban", 
        "latin music", 
        "latina",
        'latin urban / reggaeton',
        'latin urban',
        'latin pop',
        'salsa',
        'latin / pop',
        "bachata",
        "bossa nova",        
        ],
    "Metal": [
        "metal",
        "black metal",
        "death metal",
        "doom metal",
        "gothic metal",
        "heavy metal",
        "metal/hard rock",
    ],
    "New age": [
        "ambient / new age - meditation",
        "chill out",
        "meditation",
        "meditation music",
        "new age",
        "new age / meditation",
        "relaxation - meditation",
    ],
    "News & Politics": ["news & politics"],
    "Opera": [
        "opera",
        "seattle opera",
    ],
    "Piano": ["piano", "piano day", "piano improvisation", "piano solo", "solo piano"],
    "Podcasts & Talk Shows": [
        'poetry',    
        "food and drink",
        "advice",
        "radio show",
        "spoken word/speeches",    
        "education",
        "sonzeira radio show",
        "outdoor adventure",
        "argentine football",    
        'public radio',    
        "ege podcast",
        "travel",
        "conversation",
        "entertainment",
        "entrepreneurship",
        "harvard",
        "howard",
        "howard stern",
        "interview",
        "learning",
        "ltu premiere",
        "needle exchange",
        "news",
        "night owl radio",
        "noisia radio",
        "philosophy",
        "podcast",
        "preaching",
        "radioshow",
        "religion & spirituality",
        "rinse fmradio",
        "spoken word",
        "sport",
        "sports",
        "vlogmusic",
        "بودكاست",
        "radio",
    ],
    "Pop": [
        "pop",
        "dream pop",
        ],
    "asian pop": ["j-pop", "k-pop"],
    "Psytrance": [
        "progressive psytrance",
        "psy trance",
        "psy-trance",
        "psychedelic trance",
        "psytrance",
        'psy chill',
    ],
    "Punk": [
        "emo", 
        "punk"
    ],
    "R&B/Soul/Funk": [
        "funk",
        "funk bh",
        "future funk",
        "phonk",
        "r & b",
        "r&b",
        "r&b & soul",
        "r&b/soul",
        "rnb",
        "soul",
        "soulection",
        'rnbass',
        'funk carioca',        
    ],
    "Reggae": [
        "dancehall", 
        "dub", 
        "reggae", 
        "reggaeton", 
        "riddim",
        'soca'
    ],
    "Remix": ["mashup", "mix", "remix", "remixes",],
    "Rock": [
        "pop rock", 
        "post rock", 
        "progressive rock",
        "rock", 
        "rock/pop",
        "new wave",        
        ],
    "Soundtrack": [
        "score",
        "soundtracks: video games",
        "soundtrack",
        "cinematic",
        "colonna sonora",
        "film",
        "film music",
        "film score",
        "filmscore",
        "musiques de films",
        "soundtracks",
        "soundtracks/cast albums",
        "soundtracks/other",
        "soundtracks: movie soundtracks",
        "trailer",
        "tv",
        "tv music",
    ],
    "Sports": ["baseball", "sports"],
    "Storytelling": ["storytelling"],
    "Techno": [
        'techno - raw, deep, hypnotic',
        'deep techno',
        "acid",
        "dub techno",
        "frenchcore",
        "hard techno",
        "hardcore techno",
        "house & techno",
        "house techno",
        "industrial",
        "melodic house & techno",
        "melodic techno",
        "minimal / deep tech",
        "minimal techno",
        "tech house",
        "tech house - deep techacid",
        "tech-house",
        "techno",
        "techno / tech house",
        "techno / tech house / house",
        "techno house",
        "techno/electronica",
        "trance, tech-trance, techno",
    ],
    "Trance": [
        "melodic dubstep",
        "progressive",
        "progressive trance",
        "psy-trance",
        "psychedelic trance",
        "trance",
        "trance & progressive",
        "trance, tech-trance",
    ],
    "Drum & bass": [
        "breakbeat", 
        "drum & bass", 
        "drum and bass",
        "drumstep",
        'dnb',
        'breaks',
        'jungle',
        'jump up',
        'neurofunk',
        'dance - breakbeat / drum & bass - jungle',
    ],
    "Epic": ["epic", "epic music", "production music"],
    "Miscellaneous": [
        "<3",
        "babiczstyle",
        "bassline",
        "collab",
        "collaboration",
        "demo",
        "dim mak records",
        "djr7",
        "dtw",
        "experimental",
        "free download",
        "g-mafia records",
        "getting deeper",
        "grooveclowd",
        "hoodinternet",
        "hybrid",
        "kanaval",
        "katahaifisch",
        "melodic",
        "miscellaneous",
        "mor",
        "music",
        "muzenga records",
        "nan",
        "night owl radio",
        "pan",
        "plezikanaval",
        "premiere",
        "premiere tbx",
        "prspct",
        "ra",
        "resident advisor",
        "rise records",
        "royalty free music",
        "sesh",
        "soulection",
        "source to cycle",
        "steve",
        "terror",
        "the broadest beats",
        "thizzler",
        "track of the day",
        "trommel",
        "tropical",
        "type 91",
        "undertale",
        "up club records",
        "∞ ♥",
        'original',
        'cover',
        'horror',
        'culture',
        'darker than wax',
        'industrial hardcore',
        'edit',
        'love',
        'traxsource',
        'sample pack',
        '8dio',
        'rinse fm',
        'groove',
        '1btn',
        'improvisation',
        'gabber',
        'fact',
        'melbourne',
        'tlk style :-d',
        'jadū',
        'rbma',
        'hypercolour',
        'elevation',
        'psychedelic',
        'live',
        'dark disco',
        'liquidcinema',
        'golddiggerrecs',
        'brand x music',
        'eg spotlight',
        'zs',
        'beat serie gold',
        'boiler room',
        'ballad',
        'rave',
        'slight',
        'composers',
        'dj r7',
        'classical guitar',
        'dj mix',
        'vibes',
        'glitch',
        'jazz: contemporary jazz',
        'colour bass',
        'tech',
        'uk bass',
        'guaracha',
        'release',
        'footwork',
        'exclusive',
        'future beats',
        'exchange',
        'kannibalen radio',
        'free',
        "faixa",
        "liveset",
        "nerdcore",
        "zenon",
        "razor-n-tape",
        "sound effects",
        "lounge",
        "pleinvrees",
        "brohouse",
        "heartfeldt radio",
        "eclectic",
        "sound design",
        "sts9",
        "dark psy",
        "lokosound",
        "epidemic sound",
        "percussion",
        "enhanced sessions",
        "3000 deep",
        "mobilee",
        "truth",
        "scfirst",
        "drum&bass",        
    ],
    "Trailer": ["trailer music", "trailermusic"],
    "Video game music": [
        "chiptune",
        "game",
        "game music",
        "n64",
        "vgm",
        "video game",
        "video game music",
        "video games",
    ],
    "World": [
        "arabic", 
        "hindustani", 
        "world",
        "world music", 
        "طلال مداح",
        'carnatic',
        'afrobeat',
        'kanaval 2016',
        'native flute',
        "afrobeats",
        "brazil",        
    ],
}


GENRE_RENAME = {}